
import { ArrowRight, Play, Zap, BarChart3, ShieldCheck, LayoutDashboard } from 'lucide-react';
import { Link } from 'react-router-dom';
import Navbar from '../components/Navbar';
import { useTranslation } from 'react-i18next';

const LandingPage = () => {
  const { t } = useTranslation();

  return (
    <div className="min-h-screen bg-slate-50">
      <Navbar />
      
      {/* Hero Section */}
      <section className="relative overflow-hidden pt-24 pb-24 lg:pt-40 lg:pb-40">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full h-full -z-10">
          <div className="absolute top-0 left-1/4 w-[500px] h-[500px] bg-violet-200/30 rounded-full blur-3xl opacity-50 animate-pulse"></div>
          <div className="absolute bottom-0 right-1/4 w-[600px] h-[600px] bg-purple-200/30 rounded-full blur-3xl opacity-50 animate-pulse delay-1000"></div>
        </div>
        
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center">
            <h1 className="text-6xl lg:text-8xl font-black text-slate-900 tracking-tight mb-8 leading-[1.1]">
              {t('AI-Powered')} <span className="text-transparent bg-clip-text bg-gradient-to-r from-violet-600 to-purple-600">{t('Product Analysis')}</span>
            </h1>
            <p className="max-w-2xl mx-auto text-xl text-slate-500 mb-12 leading-relaxed font-medium">
              {t('Unlock deep insights into your product lifecycle with our advanced AI tools. Optimize your strategy and accelerate growth with data-driven decisions.')}
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-6">
              <Link to="/login" className="w-full sm:w-auto px-10 py-5 bg-violet-600 text-white font-black rounded-2xl hover:bg-violet-700 transition-all shadow-2xl shadow-violet-200 flex items-center justify-center gap-3 text-lg group">
                {t('Start Free Trial')}
                <ArrowRight className="w-6 h-6 group-hover:translate-x-1 transition-transform" />
              </Link>
              <button className="w-full sm:w-auto px-10 py-5 bg-white text-slate-700 font-black rounded-2xl border-2 border-slate-100 hover:border-violet-600 hover:text-violet-600 transition-all flex items-center justify-center gap-3 text-lg shadow-sm">
                <Play className="w-6 h-6 fill-violet-600 text-violet-600" />
                {t('Watch Demo')}
              </button>
            </div>
          </div>

          <div className="mt-28 relative mx-auto max-w-6xl">
            <div className="rounded-[2.5rem] border-8 border-white/50 bg-white/30 backdrop-blur-sm p-4 shadow-[0_40px_100px_-20px_rgba(0,0,0,0.15)] overflow-hidden">
              <img 
                src="https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=2426" 
                alt={t("Dashboard Preview")}
                className="rounded-[1.5rem] shadow-2xl"
              />
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-32 bg-white relative overflow-hidden">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center mb-24">
            <h2 className="text-4xl lg:text-5xl font-black text-slate-900 mb-6">{t('Ready to revolutionize your workflow?')}</h2>
            <p className="text-xl text-slate-500 font-medium">{t('Everything you need to analyze and scale your products.')}</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-10">
            {[
              {
                icon: <Zap className="w-8 h-8 text-violet-600" />,
                title: t("AI Analysis"),
                description: t("Leverage state-of-the-art machine learning models to analyze product performance automatically.")
              },
              {
                icon: <BarChart3 className="w-8 h-8 text-violet-600" />,
                title: t("PAS Framework Pulse"),
                description: t("Track your progress with the Problem-Agitation-Solution framework metrics in real-time.")
              },
              {
                icon: <ShieldCheck className="w-8 h-8 text-violet-600" />,
                title: t("Comprehensive Logs"),
                description: t("Full visibility into every action and insight generated by the system for maximum auditability.")
              }
            ].map((feature, i) => (
              <div key={i} className="p-10 rounded-[3rem] border border-slate-50 bg-slate-50/50 hover:bg-white hover:border-violet-100 hover:shadow-2xl hover:shadow-violet-100 transition-all duration-500 group">
                <div className="w-16 h-16 bg-white rounded-2xl shadow-lg shadow-slate-200/50 flex items-center justify-center mb-8 group-hover:scale-110 transition-transform duration-500">
                  {feature.icon}
                </div>
                <h3 className="text-2xl font-black text-slate-900 mb-4">{feature.title}</h3>
                <p className="text-slate-500 font-medium leading-relaxed">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Trust Section */}
      <section className="py-24 bg-slate-50">
        <div className="max-w-7xl mx-auto px-6 flex flex-col items-center">
          <p className="text-xs font-black text-slate-400 uppercase tracking-[0.3em] mb-16 text-center">
            {t('Trusted by world-class teams')}
          </p>
          <div className="flex flex-wrap justify-center gap-16 opacity-40 grayscale hover:grayscale-0 transition-all duration-700">
            {['Acme Corp', 'Global Dynamics', 'Synergy Inc', 'TechFlow', 'Stark Industries'].map((brand) => (
              <span key={brand} className="text-3xl font-black text-slate-300 hover:text-violet-600 cursor-default transition-colors">{brand}</span>
            ))}
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-20 bg-white border-t border-slate-50">
        <div className="max-w-7xl mx-auto px-6">
          <div className="flex flex-col md:flex-row justify-between items-center gap-12 pb-16">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-violet-600 rounded-xl flex items-center justify-center shadow-lg shadow-violet-100">
                <LayoutDashboard className="text-white w-6 h-6" />
              </div>
              <span className="text-2xl font-black text-slate-900 tracking-tight">PASlytics</span>
            </div>
            <div className="flex flex-wrap justify-center gap-10 text-slate-500 font-bold text-sm">
              <a href="#" className="hover:text-violet-600 transition-colors uppercase tracking-widest">{t('Privacy Policy')}</a>
              <a href="#" className="hover:text-violet-600 transition-colors uppercase tracking-widest">{t('Terms of Service')}</a>
              <a href="#" className="hover:text-violet-600 transition-colors uppercase tracking-widest">{t('Contact Support')}</a>
            </div>
          </div>
          <div className="pt-8 border-t border-slate-50 flex flex-col md:flex-row justify-between items-center gap-4">
            <p className="text-slate-400 font-bold text-sm">
              © 2026 PASlytics
            </p>
            <div className="flex gap-4">
              <div className="w-10 h-10 rounded-full bg-slate-50 flex items-center justify-center hover:bg-violet-50 hover:text-violet-600 transition-colors cursor-pointer">
                <Zap className="w-5 h-5" />
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default LandingPage;
